name: Create Release
on:
  push:
    tags:
      - "v*"

jobs:
  create:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs: [create]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: npm ci --no-audit --ignore-scripts
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
